[project]
name = "stx-freelance-platform"
description = "Decentralized freelance platform on Stacks blockchain"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []
boot_contracts = []

[contracts.escrow-contract-v1]
path = "contracts/escrow-multi-token.clar"
clarity_version = 2
epoch = "2.4"

[contracts.stxworx-v1]
path = "contracts/stxworx-badge.clar"
clarity_version = 2
epoch = "2.4"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
